version: '2'
services:
  web:
    image: nginx:1.13.12-alpine
    volumes:
      - ./ui-ng/dist:/www
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "8080:80"
    environment:
      - NGINX_HOST=mercury.com
      - NGINX_PORT=80
    links:
      - api:api

  api:
    build:
      context: .
      dockerfile: api.dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./api:/api
    depends_on:
      - postgres
    env_file: dev.env
    command: /bin/sh -c "npm run db:migrate && npm run start"

  postgres:
    image: postgres:10.3-alpine
    env_file: dev.env
